### PR TITLE
cleaned up graph styles. fixes #24

### LINKED ISSUE #24: Add comparative data
In popup and on report page, add some comparisons for the soum relative to its cluster (if it's in one), and relative to the whole country. This will only be for select indicators - tbd.

### PR DESCRIPTION
**Pull request by designmatty**
screen shot 2016-09-30 at 11 22 15 am

### CODE REVIEW

**Comment by jbranigan** [comment]
Matt, I had some different ideas about how this could be configured - should have chatted with you about it more. The graph itself has only four pieces of data (lines, distribution shading), and can probably be about half that size horizontally, and maybe a bit shorter. This would allow the numbers in the legend to be larger, gaining more prominence, and maybe they could be vertically stacked on the side, after the graph is down to a reasonable size. The numbers are the important part - the graph is a visual aid that provides a bit more context.

**Comment by designmatty** [comment]
@jbranigan, I resized the chart to have a height of 150px and moved the legend on the right of the chart. Let me know what you think of this stype of layout/design before I commit anything up.

screen shot 2016-10-03 at 12 06 54 pm

**Comment by designmatty** [comment]
Do I have the go ahead on a merge?

**Comment by rmartz** [comment]
I'd like to merge in my changes for the SVG clipping problem first, in #40. Those seem good to go but do you mind checking them out in `feature/scalable-svgs` to make sure I didn't break your styles?

**Comment by designmatty** [comment]
Just checked them out... they look good to me.

**Comment by rmartz** [comment]
Alright, I'll go ahead and merge that into here and you have my seal of approval :+1:

**Pull request merged**
