### PR TITLE
Feature/scaffold data page

### PR DESCRIPTION
**Pull request by CloudNiner**

### CODE REVIEW

**Comment by rmartz** [comment]
I'm not seeing any change for different soum, is this all only behind the scenes changes or should some of it be reflected by the UI?

**Comment by CloudNiner** [comment]
All behind the scenes, this just adds in the map on that page and hooks up the url route

**Comment by rmartz** [comment]
I feel a bit concerned about having to comment out a test, hopefully we can figure what's going on there. Otherwise LGTM

**Comment by CloudNiner** [comment]
Typically for these much smaller projects we'll only write tests for particularly complicated or brittle components to save time. Not too worried about it here.

**Pull request merged**
